### ISSUE TITLE
这是客户端？

### ISSUE THREAD

**Issue by buzai** [oyyd/encryptsocks#37]

**Comment by oyyd** [comment]
都有。我把这个issue变成一个question吧。

**Comment by buzai** [comment]
@oyyd 我看了现在的管理ｓｓ一些工程，他们的做法是启动了ｐｙｔｈｏｎ和，通过ｊｓ调用ｐｙｔｈｏｎ工程暴露的ｃｌｉ进行相应的管理，业务逻辑很繁琐．
用这个ｊｓ服务端做的话应该简单很多

**Comment by oyyd** [comment]
要用脚本处理核心特性以外的东西的话，直接调用c版本的性能最好。这个项目更多还是我自己在用，同时期望可以帮助熟悉js代码的同学更容易理解其原理。

**Comment by buzai** [comment]
@oyyd 那我在你的实现逻辑里加入业务逻辑是不是最简单的管理ｓｓ的方法了

**Comment by oyyd** [comment]
取决与你要做什么了
